### ISSUE TITLE
Problem after building apk

### ISSUE THREAD

**Issue by GekoCH** [rick51231/unifi-protect-android-direct#3]
First I used the available APK to install on the device. However I get an error "App not installed".
Then I tried to do the patching by myself and built a new APK. However after transfering it to my device I get this error "There was a problem while parsing the package."
Last I used the adb command to push the file to the device and install it via the cmd of windows. However this error appeard:
`Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]`

**Comment by GekoCH** [comment]
ok I manged to get rid of the message by using:
`zipalign 4 protect-patched.apk protect-patched_new.apk`

`Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package com.ubnt.unifi.protect]`

After a while of searching I noticed that jarsigner signs V1 (Jar Signature) But at android 11+ V2 (Full APK Signature) is required.
So how can I fix that?

**Comment by GekoCH** [comment]
ok I solved the problem by myself. Installed an App called apk-singer on my phone to resign the app. Afterwards I was able to install it

**Comment by Sverto** [comment]
Fyi, I also ran into this. It is advised to use "apksigner" (uses version 2) instead of "jarsigner" for newer android versions.
